### ISSUE TITLE
Invoking `ec2-exposed-vpc-endpoints` fails with an error

### ISSUE THREAD

**Issue by tovbinm** [faros-ai/faros-apps#25]
**Describe the bug**
Execution of `ec2-exposed-vpc-endpoints` fails with an error.

**To Reproduce**
`faros app invoke ec2-exposed-vpc-endpoints -g`

**Expected behavior**
The invocation should not fail but return some results.

**Logs or screenshots**
```sh
$ faros app invoke ec2-exposed-vpc-endpoints -g
{
  "errorMessage": "string indices must be integers",
  "errorType": "TypeError",
  "stackTrace": [
    "  File \"/var/task/app.py\", line 32, in lambda_handler\n    return [\n",
    "  File \"/var/task/app.py\", line 34, in <listcomp>\n    if check_statement(e[\"policyDocument\"][\"Statement\"])\n"
  ]
}
```

**Comment by mtth** [comment]
`policyDocument` is a string so [this line](https://github.com/faros-ai/faros-apps/blob/ee8dffc1e1e01d9e17d1926a832f37c61bf4f489/apps/ec2-exposed-vpc-endpoints/app.py#L34) needs to be updated. However, it's unclear how to find the `Principal` field needed to do the filtering. Were fields removed since the app was built?
